name: Zhp.Office.AccountManagement

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      
      - name: Build
        run: dotnet build --configuration Release automation/Zhp.Office.AccountManagement

      - name: Test
        run: dotnet build --configuration Release automation/Zhp.Office.AccountManagement
      
      - name: Prepare publish package
        run: dotnet publish --configuration Release --output app automation/Zhp.Office.AccountManagement/Zhp.Office.AccountManagement

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: App
          path: app
