name: Zhp.Office.AccountManagement

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Build
        run: dotnet build --configuration Release automation/Zhp.Office.AccountManagement

      - name: Test app
        run: dotnet test --configuration Release automation/Zhp.Office.AccountManagement

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Test ARM
        uses: azure/arm-deploy@v1
        with:
          deploymentMode: Validate
          subscriptionId: 69111246-db23-463c-82b2-7815ed5f8a1a # todo which subscription?
          resourceGroupName: office-accountmanagement
          template: automation/Zhp.Office.AccountManagement/deployment.arm.json
          parameters: JiraPassword='${{ secrets.JIRA_API_PASSWORD }}' ActiveDirectoryCertBase64='${{ secrets.AAD_APP_CERTIFICATE }}' ActiveDirectoryCertPassword='${{ secrets.AAD_APP_CERTIFICATE_PASSWORD }}'
          # region:


      - name: Prepare publish package
        run: dotnet publish --configuration Release --output app automation/Zhp.Office.AccountManagement/Zhp.Office.AccountManagement

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: App
          path: app
