name: Zhp.Office.AccountManagement

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: dotnet build --configuration Release automation/Zhp.Office.AccountManagement

    - name: Test app
      run: dotnet test --configuration Release automation/Zhp.Office.AccountManagement

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Test ARM
      uses: azure/arm-deploy@v1
      with:
        deploymentMode: Validate
        subscriptionId: 35e22786-93ea-47c8-902a-16e9d0f03e17
        resourceGroupName: office-accountmanagement
        template: automation/Zhp.Office.AccountManagement/deployment.arm.json
        parameters: JiraPassword='${{ secrets.JIRA_API_PASSWORD }}' ActiveDirectoryCertBase64='${{ secrets.AAD_APP_CERTIFICATE }}' ActiveDirectoryCertPassword='${{ secrets.AAD_APP_CERTIFICATE_PASSWORD }}'

    - name: Prepare publish package
      run: |
        dotnet publish --configuration Release --output app automation/Zhp.Office.AccountManagement/Zhp.Office.AccountManagement &&
        cp automation/Zhp.Office.AccountManagement/deployment.arm.json app/

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: App
        path: app

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/master'
    needs: build
    steps:
    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: App

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy ARM
      uses: azure/arm-deploy@v1
      with:
        deploymentMode: Complete
        subscriptionId: 35e22786-93ea-47c8-902a-16e9d0f03e17
        resourceGroupName: office-accountmanagement
        template: deployment.arm.json
        parameters: JiraPassword=${{ secrets.JIRA_API_PASSWORD }} ActiveDirectoryCertBase64=${{ secrets.AAD_APP_CERTIFICATE }} ActiveDirectoryCertPassword=${{ secrets.AAD_APP_CERTIFICATE_PASSWORD }}

    - name: Upload files
      uses: Azure/functions-action@v1
      with:
        app-name: zhp-officeaccounts
        package: .
